name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: deploy-cloud-function
  cancel-in-progress: false

jobs:
  deploy-cloud-function:
    name: Deploy Cloud Function
    runs-on: ubuntu-latest
    environment: deploy
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/283679649768/locations/global/workloadIdentityPools/github-actions/providers/github-actions
        service_account: deploy@mail-sender-442416.iam.gserviceaccount.com

    - name: Deploy Cloud Function
      run: |
        gcloud beta functions deploy send-email \
          --log-http \
          --gen2 \
          --trigger-http \
          --runtime=go122 \
          --region=europe-west2 \
          --source=. \
          --entry-point=SendEmail \
          --service-account=send-email@mail-sender-442416.iam.gserviceaccount.com \
          --quiet << EOF
        Y
        EOF
